import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "./providers/ReacrQueryProvider";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const ArialBold = localFont({
  src: "../public/fonts/Arial_Bold.ttf",
});

export const Arial = localFont({
  src: "../public/fonts/arial.ttf",
});

export const Eurostile_Extended_Regular = localFont({
  src: "../public/fonts/Eurostile_Extended_Regular.ttf",
});

export const variableFont = localFont({
  src: "../public/fonts/good_timing_bd.ttf",
});

export const TextMedium = localFont({
  src: "../public/fonts/GESSTextMedium.otf",
});

export const TextBold = localFont({
  src: "../public/fonts/GESSTextBold.otf",
});

export const TextLight = localFont({
  src: "../public/fonts/stc.otf",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ReactQueryProvider>
  );
}
